projeto01/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings





urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('recipes/', include('recipes.urls')),
   
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path
from . import views



app_name = 'recipes'
urlpatterns = [
    path('', views.home, name="home"), #/home
    path('recipes/category/<int:category_id>/',
          views.category, name="category"),
    path('recipes/<int:id>/', views.recipe, name="recipe"),
    ]

recipes/models.py
from django.db import models
from django.contrib.auth.models import User

class category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name

class recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField()
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    serving_unit = models.IntegerField(max_length=65)
    serving = models.IntegerField()
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to='recipes/covers/%Y/%m/%d')
    category = models.ForeignKey(category, on_delete=models.SET_NULL, null = True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null = True)


    def __str__(self):
        return self.title



#EDITED
#title desciption slug
#preparation_time preparation_time_unit
#serving serving_unit
#preparation_step
#preparation_step_is_html
#created_at update_at
#is_published
#cover
#category (relaçao)
# author (relaçao)

recipes/views.py
from django.shortcuts import render
from utils.recipes.factory import make_recipe

from .models import recipe

def home(request):
     recipes = recipe.objects.all().order_by('-id')
     return render(request, 'recipes/pages/home.html', context={
         'recipes': recipes,
     })

def category(request, category_id):
     recipes = recipe.objects.filter(
         category__id=category_id
     ).order_by('-id')
     return render(request, 'recipes/pages/home.html', context={
         'recipes': recipes,
     })

recipes/templates/recipes/pages/home.html
{% extends 'global/base.html' %}

{% block title %}Home |{% endblock title %}

{% block content %}
<div class="main-content main-contet-list container">
        {% for recipe in recipes %}
            {% include "recipes/partial/recipe.html" %}
        {% endfor %}
</div>
{% endblock content %}

recipes/templates/recipes/pages/recipe-view.html
{% extends 'global/base.html' %}

{% block title %}Recipes |{% endblock title %}
{% block content %}
    <div class="main-content main-content-detail container">
        {% include "recipes/partial/recipe.html" %}
    </div>
{% endblock content %}

recipes/templates/recipes/partial/footer.html
<footer class="main-footer">
    <a href="https://github.com/brunosantospaz" class="main-footer-text">Powered by Bruno Santos</a>
</footer>

recipes/templates/recipes/partial/head.html
{% load static %}

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/solid.min.css" integrity="sha512-6mc0R607di/biCutMUtU9K7NtNewiGQzrvWX4bWTeqmljZdJrwYvKJtnhgR+Ryvj+NRJ8+NnnCM/biGqMe/iRA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/brands.min.css" integrity="sha512-G/T7HQJXSeNV7mKMXeJKlYNJ0jrs8RsWzYG7rVACye+qrcUhEAYKYzaa+VFy6eFzM2+/JT1Q+eqBbZFSHmJQew==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/fontawesome.min.css" integrity="sha512-giQeaPns4lQTBMRpOOHsYnGw1tGVzbAIHUyHRgn7+6FmiEgGGjaG0T2LZJmAPMzRCl+Cug0ItQ2xDZpTmEc+CQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">
    
<link rel="preconnect" href="https://fonts.googleapis.com">
     <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
     <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">

<link rel="stylesheet" href="{% static 'recipes/CSS/styles.css' %}">

recipes/templates/recipes/partial/header.html
<header class="main-header-container">
    <div
        class="main-header container">
         <h1>
             <a class="main-logo" href="{% url 'recipes:home' %}"><i class="fas fa-utensils main-logo-icon"></i>
             <span class="main-logo-text"> Recipes</span>
             </a>
         </h1>
    </div>
 </header>

recipes/templates/recipes/partial/recipe.html
<div class="recipe recipe-list-item">
    <div class="recipe-cover"><a href="{% url 'recipes:recipe' recipe.id %}"> <img src="{{recipe.cover.url}}" alt="temporario"></a>
    </div>
    <div class="recipe-title-container">
        <h2 class="recipes-title">
            <a href="{% url 'recipes:recipe' recipe.id %}">{{ recipe.title}}
            </a>
        </h2>
    </div>

    <div class="recipe-author">
        <span class="recipes-author-item">
            <i class="fa-sharp fa-solid fa-user"></i>
            {% if recipe.author.first_name %} 
                {{recipe.author.first_name}} {{recipe.author.last_name}}
            {% else %}
                {{recipe.author.username}}
            {% endif %}
        </span>
        <span class="recipe-author-item">
            <i class="fas fa-calendar-alt"></i>
            {{ recipe.created_at|date:"d/m/Y" }}
        </span>
        <span class="recipe-author-item">
             <a href="{% url 'recipes:category' recipe.category.id %}"><i class="fa-sharp fa-solid fa-layer-group"></i><span>{{recipe.category.name}}</span>
             </a> 
        </span>
    </div>
    <div class="recipe-content">
        <p>{{recipe.description}}
        </p>
    </div>
    <div class="recipe-meta-container">
        <div class="recipe-meta precipe-pnreparatio">
            <h3 class="recipe-meta-title"><i class="fa-sharp fa-solid fa-stopwatch"></i> Preparo</h3>
            <div class="recipe-meta-text">{{ recipe.preparation_time }} {{recipe.preparation_time_unit}}</div>
        </div>
        <div class="recipe-meta recipe-servings">
            <h3 class="recipe-meta-title"><i class="fa-sharp fa-solid fa-pizza-slice"></i> Porções</h3>
            <div class="recipe-meta-text">{{ recipe.servings }} {{ recipe.serbvings_unit }}</div>
        </div>
    </div>
    
    {% if is_detail_page is not True %}
    <footer class="recipe-footer">
        <a href="{% url 'recipes:recipe' recipe.id %}" class="recipre-read-more button-dark button-full-width"><i class="fa-sharp fa-solid fa-eye"></i><span>Ver mais...</span>
        </a>
    </footer>
    {% endif %}

    {% if is_detail_page is True %}
        <div class="preparation-steps">
            {{ recipe.preparation_steps|linebreaksbr }}
        </div>
    {% endif %}


</div>

recipes/templates/recipes/partial/search.html
<div class="search-container"></div>
    <div class="container">
        <form action="" class="search-form">
            <input type="search" class="search-input" nome="search">
            <button type="submit" class="search-button"><i class="fas fa-search"></i>
            </button>
        </form>
    </div>